Pages/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EagleFlight.Pages
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/AjaxsearchResultTwo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EagleFlight.Data;
using EagleFlight.Models;
using Microsoft.Extensions.Logging;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace EagleFlight.Pages
{
    public class AjaxsearchResultTwoModel : PageModel
    {
        private readonly EagleFlightDbContext db; 
        private readonly ILogger<IndexModel> logger;

        public AjaxsearchResultTwoModel(EagleFlightDbContext db, ILogger<IndexModel> logger)
        {
            this.db = db;
            this.logger = logger;  
        }

        public List<Flight> FlightSearchList { get; set; } = new List<Flight>();

        [BindProperty(SupportsGet =true)]
        public String OriginLocation { get; set; }

        [BindProperty(SupportsGet =true)]
        public String ArriveLocation { get; set; }

        [BindProperty(SupportsGet =true),Required, Display(Name="DepartureDate")]
        public DateTime DepartureDate { get; set; }

        [BindProperty(SupportsGet =true)]
        public DateTime ArriveTime { get; set; }

        [BindProperty(SupportsGet =true)]
        public string FlightClass { get; set; }
        [BindProperty(SupportsGet =true)]
        public string FlightId { get; set; }

        [BindProperty]
        public string FlightClassTwo { get; set; }
        [BindProperty]
        public string FlightIdTwo { get; set; }

        [BindProperty(SupportsGet =true)]
        public string TripType { get; set; }

        public async Task OnGetAsync()
        {
            // FlightSearchList = await db.Flights.Join(db.Planes, Flight =>Flight.FlightPlane.Id, Plane => Plane.Id,(Flight,Plane) =>new{Flight,Plane}).Where(u =>u.Origin == OriginLocation && u.Destination == ArriveLocation && u.DepartureTime.Date == DepartureDate.Date).ToListAsync();
            FlightSearchList = await db.Flights.Include(Flight => Flight.FlightPlane).Where(u =>u.Origin == OriginLocation && u.Destination == ArriveLocation && u.DepartureTime.Date == DepartureDate.Date).ToListAsync();
        }

        public async Task<IActionResult> OnPostAsync()
        {
        if (ModelState.IsValid)
        {            
            logger.LogInformation($"flightId: {FlightId}");
            logger.LogInformation($"flightClass: {FlightClass}");
            logger.LogInformation($"flightIdTwo: {FlightIdTwo}");
            logger.LogInformation($"flightClassTwo: {FlightClassTwo}");
            return RedirectToPage("/TicketSummary", new { FlightId = FlightId, FlightClass = FlightClass,TripType=TripType,FlightIdTwo = FlightIdTwo, FlightClassTwo = FlightClassTwo});
            
        }
        return Page();
        }
    }
}

Pages/BookTicketSuccess.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EagleFlight.Models;
using EagleFlight.Data;
using Microsoft.Extensions.Logging;

namespace EagleFlight.Pages
{
    public class BookTicketSuccessModel : PageModel
    {
        private readonly EagleFlightDbContext db; 
        private readonly ILogger<TicketSummaryModel> logger;

        public BookTicketSuccessModel(EagleFlightDbContext db, ILogger<TicketSummaryModel> logger)
        {
            this.db = db;
            this.logger = logger;  
        }

        public Ticket xtt = TicketSummaryModel.newTicket;
        public Ticket xtt2 = TicketSummaryModel.newTicketTwo;

        public void OnGet()
        {

            db.Tickets.Add(xtt);
            db.SaveChangesAsync();
            db.Tickets.Add(xtt2);
            db.SaveChangesAsync();

        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace EagleFlight.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using EagleFlight.Data;
using EagleFlight.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EagleFlight.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly EagleFlightDbContext _dbContext;



        public bool isOnSearch { get; set; }
        public bool foundMatch { get; set; }

        public IndexModel(EagleFlightDbContext DbContext, ILogger<IndexModel> Logger)
        {
            _dbContext = DbContext;
            _logger = Logger;
            oList = _dbContext.Flights.Select(r => r.Origin).Distinct().ToList();
            oList.Sort();
            dList = _dbContext.Flights.Select(r => r.Destination).Distinct().ToList();
            dList.Sort();
            this.DepartureDate = DateTime.Today;
            this.departureDateOneWay = DateTime.Today;
            this.UpComingFlighList = _dbContext.Flights.OrderBy(o => o.DepartureTime).Where(r => DateTime.Compare(r.DepartureTime, DateTime.Now) >= 0 && DateTime.Compare(r.DepartureTime, DateTime.Now) < 10).ToList();
        }

        public List<string> oList { get; set; }
        public List<string> dList { get; set; }


        [BindProperty] 
        public String TripType { get; set; }
        [BindProperty, Required]
        public String Origin { get; set; }

        [BindProperty, Required]
        public String Destination { get; set; }

        [BindProperty, Required, Display(Name = "DepartureDate")]
        public DateTime DepartureDate { get; set; }

        [BindProperty, Required, Display(Name = "ReturnDate")]
        public DateTime ReturnDate { get; set; }

        [BindProperty]
        public DateTime departureDateOneWay { get; set; }

        [BindProperty]
        public int SelectFlightId { get; set; }
        public List<Flight> UpComingFlighList;

        public void OnGet()
        {

        }

        public IActionResult OnPost()
        {

            if (DateTime.Compare(ReturnDate, DepartureDate) < 0)
            {
                ModelState.AddModelError(string.Empty, "Return date must same as or later than departure data");
            }



            if (!ModelState.IsValid)
            {
                return Page(); // PageResult();
            }
            // otherwise do some processing

            if(TripType== "1"){
            return new RedirectToPageResult("/SearchResult", new { DepartureDate = departureDateOneWay, ArriveTime = ReturnDate, OriginLocation = Origin, ArriveLocation = Destination , TripType=TripType});               
            }
            

         
            return new RedirectToPageResult("/SearchResult", new { DepartureDate = DepartureDate, ArriveTime = ReturnDate, OriginLocation = Origin, ArriveLocation = Destination , TripType=TripType});


        }

	  public IActionResult OnPostDirectBook(int sessioncount)
        {

            if (DateTime.Compare(ReturnDate, DepartureDate) < 0)
            {
                ModelState.AddModelError(string.Empty, "Return date must same as or later than departure data");
            }
         
            return new RedirectToPageResult("/SearchResult", new { DepartureDate = DepartureDate, ArriveTime = ReturnDate, OriginLocation = Origin, ArriveLocation = Destination , TripType=TripType});

        }


    }
}

Pages/InternalError.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EagleFlight.Pages
{
    public class InternalErrorModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Payment.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EagleFlight.Models;
using EagleFlight.Data;

namespace EagleFlight.Pages
{
    public class PaymentModel : PageModel
    {
        public Ticket xtt = TicketSummaryModel.newTicket;
        public Ticket xtt2 = TicketSummaryModel.newTicketTwo;
 
        public void OnGet()
        {
        }
    }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace EagleFlight.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/SearchResult.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using EagleFlight.Data;
using EagleFlight.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EagleFlight.Pages
{
    public class SearchResultModel : PageModel
    {
        private readonly EagleFlightDbContext db; 
        private readonly ILogger<IndexModel> logger;

        public SearchResultModel(EagleFlightDbContext db, ILogger<IndexModel> logger)
        {
            this.db = db;
            this.logger = logger;  
        }

        public List<Flight> FlightSearchList { get; set; } = new List<Flight>();

        [BindProperty(SupportsGet =true)]
        public String OriginLocation { get; set; }

        [BindProperty(SupportsGet =true)]
        public String ArriveLocation { get; set; }

        [BindProperty(SupportsGet =true),Required, Display(Name="DepartureDate")]
        public DateTime DepartureDate { get; set; }

        [BindProperty(SupportsGet =true)]
        public DateTime ArriveTime { get; set; }

        [BindProperty]
        public string FlightClass { get; set; }
        [BindProperty]
        public string FlightId { get; set; }

        [BindProperty(SupportsGet =true)]
        public string TripType { get; set; }

        public async Task OnGetAsync()
        {
            // FlightSearchList = await db.Flights.Join(db.Planes, Flight =>Flight.FlightPlane.Id, Plane => Plane.Id,(Flight,Plane) =>new{Flight,Plane}).Where(u =>u.Origin == OriginLocation && u.Destination == ArriveLocation && u.DepartureTime.Date == DepartureDate.Date).ToListAsync();
            FlightSearchList = await db.Flights.Include(Flight => Flight.FlightPlane).Where(u =>u.Origin == OriginLocation && u.Destination == ArriveLocation && u.DepartureTime.Date == DepartureDate.Date).ToListAsync();
        }

        public async Task<IActionResult> OnPostAsync()
        {
        if (ModelState.IsValid)
        {
            logger.LogInformation($"flightId: {FlightId}");
            logger.LogInformation($"flightClass: {FlightClass}");

            var userName = User.Identity.Name; // userName is email
            var user = db.Users.Where(u => u.UserName == userName).FirstOrDefault(); // find user record

            if(user != null){
                if(TripType == "1"){
                return RedirectToPage("/TicketSummary", new { FlightId = FlightId, FlightClass = FlightClass,TripType=TripType});
                }
                if(TripType == "0"){
                // return RedirectToPage("/TicketSummary", new { FlightId = FlightId, FlightClass = FlightClass});
                return new RedirectToPageResult("/SearchResultTripTwo", new { DepartureDate = ArriveTime, ArriveTime = DepartureDate, OriginLocation =  ArriveLocation, ArriveLocation = OriginLocation, TripType=TripType,FlightId = FlightId, FlightClass = FlightClass});
                }

            }else{
                return RedirectToPage("UserAccessDenied");
            }

        }
        return Page();
        }


    }
}

Pages/SearchResultTripTwo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EagleFlight.Data;
using EagleFlight.Models;
using Microsoft.Extensions.Logging;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace EagleFlight.Pages
{
    public class SearchResultTripTwoModel : PageModel
    {
        private readonly EagleFlightDbContext db; 
        private readonly ILogger<IndexModel> logger;

        public SearchResultTripTwoModel(EagleFlightDbContext db, ILogger<IndexModel> logger)
        {
            this.db = db;
            this.logger = logger;  
        }

        public List<Flight> FlightSearchList { get; set; } = new List<Flight>();

        [BindProperty(SupportsGet =true)]
        public String OriginLocation { get; set; }

        [BindProperty(SupportsGet =true)]
        public String ArriveLocation { get; set; }

        [BindProperty(SupportsGet =true),Required, Display(Name="DepartureDate")]
        public DateTime DepartureDate { get; set; }

        [BindProperty(SupportsGet =true)]
        public DateTime ArriveTime { get; set; }

        [BindProperty(SupportsGet =true)]
        public string FlightClass { get; set; }
        [BindProperty(SupportsGet =true)]
        public string FlightId { get; set; }

        [BindProperty]
        public string FlightClassTwo { get; set; }
        [BindProperty]
        public string FlightIdTwo { get; set; }

        [BindProperty(SupportsGet =true)]
        public string TripType { get; set; }

        public async Task OnGetAsync()
        {
            // FlightSearchList = await db.Flights.Join(db.Planes, Flight =>Flight.FlightPlane.Id, Plane => Plane.Id,(Flight,Plane) =>new{Flight,Plane}).Where(u =>u.Origin == OriginLocation && u.Destination == ArriveLocation && u.DepartureTime.Date == DepartureDate.Date).ToListAsync();
            FlightSearchList = await db.Flights.Include(Flight => Flight.FlightPlane).Where(u =>u.Origin == OriginLocation && u.Destination == ArriveLocation && u.DepartureTime.Date == DepartureDate.Date).ToListAsync();
        }

        public async Task<IActionResult> OnPostAsync()
        {
        if (ModelState.IsValid)
        {            
            logger.LogInformation($"flightId: {FlightId}");
            logger.LogInformation($"flightClass: {FlightClass}");
            logger.LogInformation($"flightIdTwo: {FlightIdTwo}");
            logger.LogInformation($"flightClassTwo: {FlightClassTwo}");
            return RedirectToPage("/TicketSummary", new { FlightId = FlightId, FlightClass = FlightClass,TripType=TripType,FlightIdTwo = FlightIdTwo, FlightClassTwo = FlightClassTwo});
            
        }
        return Page();
        }
    }
}

Pages/UserAccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EagleFlight.Pages
{
    public class UserAccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/AccessDenied.cshtml
@page
@model EagleFlight.Pages.AccessDeniedModel
@{
    ViewData["Title"] = "Access Denied";
}

<h1>@ViewData["Title"]</h1>
<p class="d-inline">Click</p>
<a class="nav-link d-inline" asp-area="" asp-page="/Index">here</a>
<p class="d-inline">to Continue!</p>  

Pages/AjaxsearchResultTwo.cshtml
@page "{DepartureDate}/{OriginLocation}/{ArriveLocation}"
@model EagleFlight.Pages.AjaxsearchResultTwoModel
@{
    Layout = null;
}
<div>
    <tbody>
    @foreach (var f in Model.FlightSearchList)
    {
    <tr>
    <td>@f.Origin</td>
    <td>@f.Destination</td>
    <td>@f.DepartureTime.ToString("yyyy/MM/dd HH:mm")</td>
    <td>@f.ArriveTime.ToString("yyyy/MM/dd HH:mm")</td>
    <td>@f.FlightType</td>
    @{ string mystringE = "a"+@f.Id.ToString();}
    <td>  <a class="btn btn-primary" data-bs-toggle="collapse" href="#@mystringE" role="button" aria-expanded="false" aria-controls="collapseExample" style="margin-bottom:20px">
        $ @f.TicketPrice</a></td> 

    @{ string mystringB = "b"+@f.Id.ToString();}
    @{double business = @f.TicketPrice * 1.5;}
    <td>  <a class="btn btn-danger" data-bs-toggle="collapse" href="#@mystringB" role="button" aria-expanded="false" aria-controls="collapseExample" style="margin-bottom:20px; background-color:red">
    $ @business</a></td>  
        
    </tr>
    <br>
    <tr>
    <td colspan="7">
        @* <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            Button with data-bs-target
        </button> *@
    <div class="collapse" id="@mystringE">
        <div class="card card-body">
            <div class="row">
                <div class ="col-md-4">
                    <img src="@f.FlightPlane.ImageFile" height="250">
                </div>
                <div class ="col-md-6">
                    <P><span style="font-weight: bold"> Flight Description: </span>@f.FlightPlane.Description</P> 
                    <P><span style="font-weight: bold">Max Passengers: </span> @f.FlightPlane.MaxPassenger</P> 
                        <form method="post">
                            <div asp-validation-summary="All" class="text-danger"></div>
                            <div class="form-group">
                                <label>Economy:</label>
                                <input class="form-control" value="$ @f.TicketPrice" readonly/>
                                <input class="form-control" asp-for="@Model.FlightClassTwo" type="hidden" value="E"/>
                                <input class="form-control" asp-for="@Model.FlightIdTwo" type="hidden" value="@f.Id"/>
                                <button  class="btn btn-primary mt-2">Select</button>
                                @* <a type="button" href="/TicketSummary/@f.Id/E" class="btn btn-outline-primary" style="width:100px">Select</a> *@
                            </div>                   
                        </form>
                </div>
            </div>
        </div>
    </div>
    <div class="collapse" id="@mystringB">
        <div class="card card-body">
            <div class="row">
                <div class ="col-md-4">
                    <img src="@f.FlightPlane.ImageFile" height="250">
                </div>
                <div class ="col-md-6">
                    <P><span style="font-weight: bold"> Flight Description: </span>@f.FlightPlane.Description</P> 
                    <P><span style="font-weight: bold">Max Passengers: </span> @f.FlightPlane.MaxPassenger</P> 
                    <form method="post">
                        <div class="form-group">
                            <label>Business:</label>
                            <input class="form-control" value="$ @business" readonly/>
                            <input class="form-control" asp-for="@Model.FlightClassTwo" type="hidden" value="B"/>
                            <input class="form-control" asp-for="@Model.FlightIdTwo" type="hidden" value="@f.Id"/>
                            <button  class="btn btn-danger mt-2">Select</button>
                        </div>                   
                    </form>
                </div>
            </div>
        </div>
    </div>
    </td>
    </tr>
    }
    </tbody> 
</div>

Pages/BookTicketSuccess.cshtml
@page
@model EagleFlight.Pages.BookTicketSuccessModel
@{
    ViewData["Title"] = "Book Ticket and Pay successfully";
}

<h3>@ViewData["Title"]</h3>
<p class="d-inline">Click</p>
<a class="nav-link d-inline" asp-area="" asp-page="/Index" style= "color:blue">here</a>
<p class="d-inline">to continue at homepage.<br> You may check your ticket information in "MY TICKET" </p>  
<br>
<p>Or, wait 3 seconds to continue at homepage automatically.</p>  

@section Scripts {
    <script> setTimeout(function() {window.location.href = "/Index";}, 3000);</script>
}

Pages/Index.cshtml
@page
@model IndexModel
@inject SignInManager<EagleFlightUser> signInManager;
@section Styles {
    <link rel="stylesheet" href="~/css/customized.css" />
}
@{
    ViewData["Title"] = "Home page";
}
<!--SHowcase-->
<section class="showcase">
    <div class="container">
        <div class="showcase-text">
            <h1>Seasonal Promotion</h1>
            <p>Our present for your summer plan, up to 75% discount on tickets! <span style="font-size: 10px;">( on
                    selected tickets)</span>
            </p>
            <a href="" class="btn btn-outline">Find Out</a>
        </div>
    </div>
</section>

<!--Search Flight-->
<div class="search-ticket-form card">
    <h2>Search For A Flight</h2>


    <form method="POST" class="row grid" id="search-ticket-criteria-form">
        <div class="col-12">
        <select name="triptype" id="tripType" class="m-3 p-1 border-d-1 col-lg-3 col-md-6 col-sd-12">
            <option value="0" selected>Round Trip</option>
            <option value="1" >One way</option>
        </select>
        </div>
        <div class="form-control border-0 grid-col13 col-lg-3 col-md-6 col-sd-12">
        <label for="">From: </label>
        <select class="border-d-1" name="origin" asp-for="Origin">
        @foreach(var o in Model.oList)
        {
            <option value="@o" name = "@o">@o</option>

        }          
        </select>
        </div>
         <div class="form-control border-0 grid-col13 col-lg-3 col-md-6 col-sd-12">
        <label for="">To : </label>
        <select class="border-d-1" name="destination"
        asp-for="Destination">
            @foreach(var o in Model.dList)
            {
                <option value="@o" name = "@o">@o</option>

            }
        </select>      
            </div>     
       
         <div class="form-control border-0 grid-col13 col-lg-3 col-md-6 col-sd-12 show-in-round-trip" >
            <label for="">Depart: </label>
            <input class=" border-d-1" asp-for="DepartureDate" type="date" name="departureDate" id="departureDate-round-trip" placeholder="Departure"
                required>
        </div>

        <div class="form-control border-0 grid-col13 col-lg-3 col-md-6 col-sd-12 show-in-round-trip" >
            <label for="">Return: </label>
            <input class=" border-d-1" asp-for="DepartureDate" type="date" name="returnDate" id="returnDate" placeholder="Return"
             required>
             <span id="returnWarmingMsg">Return must not be earilier than departure</span>
        </div>

        <div class="form-control border-0 grid-col13 col-lg-6 col-md-6 col-sd-12 show-in-one-way" >
            <label for="">DepartAt: </label>
            @* <input class=" border-d-1 col-span-2" asp-for="DepartureDate" type="date" name="departureDate" id="departureDate-one-way" placeholder="Departure"
                required> *@
            <input class=" border-d-1 col-span-2" asp-for="departureDateOneWay" type="date" placeholder="Departure"
                required>
        </div>

        <input class="btn btn-primary col-lg-3 col-md-6" type="submit" value="Search">   
        <div asp-validation-summary="All" class="text-danger"></div>
        
    </form>
</div>

<!--Upcoming Flight Tables-->
<section class="martchedFlight">
    <div class="container">
        <h2>@(Model.isOnSearch?"Matched Flights":"Upcomping Flights")</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.UpComingFlighList[0].DepartureTime)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.UpComingFlighList[0].ArriveTime)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.UpComingFlighList[0].Origin)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.UpComingFlighList[0].Destination)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.UpComingFlighList[0].FlightType)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.UpComingFlighList[0].TicketPrice)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.UpComingFlighList)
                    {
                        <tr>
                            <td>
                                @* @Html.DisplayFor(modelItem => item.DepartureTime) *@
                             @item.DepartureTime.ToString("yyyy/MM/dd HH:mm")                               
                            </td>
                            <td>
                                @* @Html.DisplayFor(modelItem => item.ArriveTime) *@
                             @item.ArriveTime.ToString("yyyy/MM/dd HH:mm")     
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Origin)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Destination)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FlightType)
                            </td>
                            <td>
                                $ @Html.DisplayFor(modelItem => item.TicketPrice)
                            </td>
                            <td>
                                @if (signInManager.IsSignedIn(User))
                                {   
                                <form method="POST">
                                <input asp-for="Origin" value="@item.Origin" class="hidden">
                                <input asp-for="Destination" value="@item.Destination" class="hidden">
                                <input type="datetime" asp-for="DepartureDate" value=@item.DepartureTime class="hidden">
                                <input asp-for="TripType" value=1 class="hidden">
                                    
                                <button type="submit" asp-page-handler="DirectBook" asp-route-sessioncount="99" class="btn btn-primary">Book</button> 
                                    </form>
                                    @* <a asp-page="./SearchResult"  class="btn btn-primary">Book a Ticket</a> *@
                                }else
                                {
                                    <a asp-page="./Account/Login" class="btn btn-primary">Login to Book</a>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
    </div>
</section>


<script src="~/js/index.js"></script>

Pages/InternalError.cshtml
@page
@model EagleFlight.Pages.InternalErrorModel
@{
    ViewData["Title"] = "Internal Error";
}

<h1>@ViewData["Title"]</h1>
<p class="d-inline">Click</p>
<a class="nav-link d-inline" asp-area="" asp-page="/Index">here</a>
<p class="d-inline">to Continue!</p>  

Pages/UserAccessDenied.cshtml
@page
@model EagleFlight.Pages.UserAccessDeniedModel
@{
    ViewData["Title"] = "User Access Denied";
}

<h1>@ViewData["Title"]</h1>
<p class="d-inline">To book a ticket you have to login first</p>
<p class="d-inline">Click</p>
<a class="nav-link d-inline" asp-area="" asp-page="/Account/Login">here</a>
<p class="d-inline">to Continue!</p>  